#!/bin/bash

# Launch Rofi
MENU="$(rofi -no-lazy-grab -sep "|" -dmenu -i -p 'System :' \
-me-select-entry '', \
-me-accept-custom 'MousePrimary', \
-markup-rows \
-no-sidebar-mode \
-bw 0 \
-lines 5 \
-line-padding 10 \
-padding 10 \
-width 10 \
-height 20 \
-xoffset 0 -yoffset -34 \
-location 5 \
<<< "<big></big> Lock|<big></big> Logout |<big></big> Sleep |<big></big> Reboot |<big></big> Shutdown ")"
case "$MENU" in
  ** ) dm-tool lock ;;
  ** ) bspc quit;;
  ** ) systemctl suspend ;;
  ** ) systemctl reboot ;;
  ** ) systemctl -i poweroff
esac

# More Options
# -fullscreen \
